const contacts={1:"5575981385005",2:"5575982738522"};document.querySelector("#menu").onclick=()=>document.querySelector("#nav").classList.toggle("open");document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>document.querySelector("#nav").classList.remove("open"));document.querySelectorAll("[data-wa]").forEach(a=>{a.href="https://wa.me/"+contacts[a.dataset.wa]+"?text="+encodeURIComponent(a.dataset.msg||"Olá! Vim pelo app da Trip Eco.")});document.querySelectorAll(".lead").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));const msg=`Olá! Quero agendar uma conversa com a Trip Eco.\n\nTipo: ${form.dataset.type}\nPessoas: ${d.pessoas}\nCidade de saída: ${d.saida}\nDestino: ${d.destino}\nPeríodo: ${d.periodo}\nPerfil do grupo: ${d.perfil||"Não informado"}\nTelefone: ${d.telefone}`;const pick=confirm("OK: falar pelo (75) 98138-5005.\nCancelar: usar (75) 98273-8522.");location.href="https://wa.me/"+(pick?contacts[1]:contacts[2])+"?text="+encodeURIComponent(msg)}));if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js"));;let deferredPrompt=null;
const ib=document.getElementById("installApp"),ih=document.getElementById("installHelp");
const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);
const standalone=window.matchMedia("(display-mode: standalone)").matches||navigator.standalone===true;
if(standalone&&ib)ib.style.display="none";
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;if(ib){ib.disabled=false;ib.textContent="📲 Instalar aplicativo Trip Eco"}if(ih)ih.textContent="Aplicativo pronto para instalar neste Android.";});
if(ib)ib.addEventListener("click",async()=>{
 if(standalone)return;
 if(deferredPrompt){deferredPrompt.prompt();const c=await deferredPrompt.userChoice;deferredPrompt=null;if(ih)ih.textContent=c.outcome==="accepted"?"Instalação iniciada.":"Instalação não concluída.";}
 else if(isiOS){if(ih)ih.innerHTML="No iPhone/iPad: abra no <b>Safari</b>, toque em <b>Compartilhar</b> e depois <b>Adicionar à Tela de Início</b>.";}
 else {if(ih)ih.innerHTML="No Android: abra esta página no <b>Google Chrome</b>, aguarde alguns segundos e toque novamente. Se necessário, atualize a página uma vez.";}
});
window.addEventListener("appinstalled",()=>{if(ih)ih.textContent="Trip Eco instalado com sucesso.";if(ib)ib.style.display="none"});